
package com.sws.springbootsoapclient.stub;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BankingPort", targetNamespace = "http://www.example.com/banking")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BankingPort {


    /**
     * 
     * @param createAccountRequest
     * @return
     *     returns com.sws.springbootsoapclient.stub.CreateAccountResponse
     */
    @WebMethod(operationName = "CreateAccount")
    @WebResult(name = "CreateAccountResponse", targetNamespace = "http://www.example.com/banking", partName = "CreateAccountResponse")
    public CreateAccountResponse createAccount(
        @WebParam(name = "CreateAccountRequest", targetNamespace = "http://www.example.com/banking", partName = "CreateAccountRequest")
        CreateAccountRequest createAccountRequest);

    /**
     * 
     * @param getAccountBalanceRequest
     * @return
     *     returns com.sws.springbootsoapclient.stub.GetAccountBalanceResponse
     */
    @WebMethod(operationName = "GetAccountBalance")
    @WebResult(name = "GetAccountBalanceResponse", targetNamespace = "http://www.example.com/banking", partName = "GetAccountBalanceResponse")
    public GetAccountBalanceResponse getAccountBalance(
        @WebParam(name = "GetAccountBalanceRequest", targetNamespace = "http://www.example.com/banking", partName = "GetAccountBalanceRequest")
        GetAccountBalanceRequest getAccountBalanceRequest);

}
