
package com.sws.springbootsoapclient.stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "BankingPortService", targetNamespace = "http://www.example.com/banking", wsdlLocation = "file:/C:/Vasu-Local/Java-Microservices/springboot-soapclient/src/main/resources/wsdl/banking.wsdl")
public class BankingPortService
    extends Service
{

    private static final URL BANKINGPORTSERVICE_WSDL_LOCATION;
    private static final WebServiceException BANKINGPORTSERVICE_EXCEPTION;
    private static final QName BANKINGPORTSERVICE_QNAME = new QName("http://www.example.com/banking", "BankingPortService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Vasu-Local/Java-Microservices/springboot-soapclient/src/main/resources/wsdl/banking.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BANKINGPORTSERVICE_WSDL_LOCATION = url;
        BANKINGPORTSERVICE_EXCEPTION = e;
    }

    public BankingPortService() {
        super(__getWsdlLocation(), BANKINGPORTSERVICE_QNAME);
    }

    public BankingPortService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BANKINGPORTSERVICE_QNAME, features);
    }

    public BankingPortService(URL wsdlLocation) {
        super(wsdlLocation, BANKINGPORTSERVICE_QNAME);
    }

    public BankingPortService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BANKINGPORTSERVICE_QNAME, features);
    }

    public BankingPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BankingPortService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BankingPort
     */
    @WebEndpoint(name = "BankingPortSoap11")
    public BankingPort getBankingPortSoap11() {
        return super.getPort(new QName("http://www.example.com/banking", "BankingPortSoap11"), BankingPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BankingPort
     */
    @WebEndpoint(name = "BankingPortSoap11")
    public BankingPort getBankingPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.com/banking", "BankingPortSoap11"), BankingPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BANKINGPORTSERVICE_EXCEPTION!= null) {
            throw BANKINGPORTSERVICE_EXCEPTION;
        }
        return BANKINGPORTSERVICE_WSDL_LOCATION;
    }

}
